### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by Filmon-gh** [Filmon-gh/TechPostHub#7]
Epic: #5
As a **user** I can access a site-wide navigation bar  so that **I can smoothly navigate from one page to another.**

# Acceptance Criteria
  - Users should be able to navigate to different pages or sections of the application using labeled links or buttons on the navigation bar.
  - Users should experience smooth and seamless transitions when navigating from one page to another using the navigation bar.
 
  
# Tasks
 - [ ] Set up a navigation component to be displayed site-wide.
 - [ ] Implement routing in the React application.
 - [ ] Integrate navigation with React Router for seamless page transitions.
